### ISSUE TITLE
A mistake in the file "sklearn-sentiment-anylisis.py"

### ISSUE THREAD

**Issue by maimogu** [zhourunlai/nlp-sentiment-analysis#1]
Firstly, thanks for your contribution !!

You can't use the function  "metrics.precision_score(actual, pred)"

It is a multiple class problem. And then the function is used in the binary problem.

I have tested the function metrics.confusion_matrix. It works..

Thank you again.

**Comment by zhourunlai** [comment]
Thannks,

You can pull the request and I will merge it.
